CREATE TABLE Employees (
Id UNIQUEIDENTIFIER NOT NULL,
FirstName VARCHAR(100) NOT NULL,
Surname VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
JobTitle VARCHAR(150) NOT NULL,
ProfileImage VARCHAR(255)
);